name: Android Build


on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set Up JDK
      with:
        java-version: 1.8


#       - name: Run Tests
#         run: ./gradlew test

       - name: Build Project
         run: ./gradlew assemble

       - name: Build the app
         run: ./gradlew build