name: Android Build


on: [pull_request, push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

#      - name: Build the app
#         run: ./gradlew build
#
#      - name: Set Up JDK
#      with:
#        java-version: 1.8
#
#
##       - name: Run Tests
##         run: ./gradlew test
      - name: Make gradlew executable
          run: chmod +x ./gradlew
            - name: Build with Gradle
              run: ./gradlew build
#
#       - name: Build Project
#         run: ./gradlew assemble
#
#       - name: Build the app
#         run: ./gradlew build